---
title: "Lab 2"
author: "Alexandra McGuire"
date: "1/29/2020"
output: html_document
---

### 1
```{r}
x <- c(1,3,6,9,12)
y <- c(1,0,1,0,1)
addition <- c(x+y)
addition
subtraction <- c(x-y)
subtraction
multiplication <- c(x*y)
multiplication
division <- c(y/x)
division
```

### 2
```{r}
vector1 <- c(0,1,2,3)
vector2 <- c("aa","bb","cc","dd")
vector3 <- c("aa",1,"bb",2)
str(vector1)
str(vector2)
str(vector3)
```

### 3
```{r}
genotype1 <- c("AA","AA","AG","GG","GG")
genotype2 <- c("AA","AA","GG","GG","GG")
genotype <-cbind(genotype1,genotype2)
genotype
table(genotype)
```

### 4
```{r}
treatment1 <- c(0,1,2,3,4)
treatment2 <- c(0,2,4,6,8)
treatment3 <- c(0,3,6,9,12)
time <- c(0,2,4,6,8)
samples <- data.frame(time, treatment1, treatment2, treatment3)
samples
plot(treatment3, time)
```

### 5
```{r}
SNP_comp <- read.table("23andMe_complete.txt", header = TRUE, sep = "\t")
SNP_comp
str(SNP_comp$chromosome)
```

different because "MT, X, Y" included in complete set as chromosome, instead of all values

### 6
```{r}
table(SNP_comp$genotype)
```

### 7
```{r}
SNP_comp_A <- subset(SNP_comp, genotype =='A')
SNP_comp_A
table(SNP_comp_A$chromosome)
```
chromosomes MT, X, and Y are the only ones with the single letter genotype A